### ISSUE TITLE
Are You really required to login to your own discord?

### ISSUE THREAD

**Issue by TheRealFame** [kocxyz/Launcher#105]
What's the integration **required** for??

**Comment by Ipmake** [comment]
Ease of use and simplicity for both users and developers. 

It is just what we chose as a very small development team since it's so easy to set up and maintain. We don't have to store passwords whatsoever or deal with brute force attacks or similar. And since our community is pretty much bound to the discord there is no reason to have chosen another.

**Comment by TheRealFame** [comment]
> Ease of use and simplicity for both users and developers. 
> 
> It is just what we chose as a very small development team since it's so easy to set up and maintain. We don't have to store passwords whatsoever or deal with brute force attacks or similar. And since our community is pretty much bound to the discord there is no reason to have chosen another.

Ugh, Then I'll review over it's requirements and see if it wants permissions I'd otherwise decline due to obvious reasons..

**Comment by Ipmake** [comment]
It only requires the bare minimum
![image](https://github.com/user-attachments/assets/ed7adc8c-7a0f-47b6-8970-3f78aab134aa)

**Comment by TheRealFame** [comment]
Seems simple enough~ But since it's discord integration and nothing unique, I'll still have to pass, As I'm moving off discord later next year. 

(Closing the issue, I do still get notifications here.)
